version: "3.9"
services:
  py-algo-workshop:
    stdin_open: true
    init: true
    environment:
      GH_TOKEN: ${GH_TOKEN}
    volumes:
      - type: volume
        source: vscode-extensions
        target: /home/dev/.vscode-server/extensions
      - type: volume
        source: vscode-extensions-insiders
        target: /home/dev/.vscode-server-insiders/extensions
    # command: /bin/sh -c "while sleep 1000; do :; done"

volumes:
  vscode-extensions:
    name: py-algo-workshop-vscode-extensions
  vscode-extensions-insiders:
    name: py-algo-workshop-vscode-insiders-extensions
